In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv('final_players_ipl_2022.csv')
df

        Player Name
0     Glenn Maxwell
1    Jasprit Bumrah
2       Tim Southee
3     Aiden Markram
4     Andre Russell
5  Liam Livingstone
6      David Warner
7       Jos Buttler
8     Rajat Patidar
9  Suryakumar Yadav

In [2]:
import pandas as pd

df2 = pd.read_csv('batting.csv')  # Replace with the actual file name
df3 = pd.read_csv('bowling.csv')  # Replace with the actual file name

df_names = df['Player Name'].tolist()
df2_names = df2['batsmanName'].tolist()
df3_names = df3['bowlerName'].tolist()

# Check names in df against df2 and df3
df['In_df2'] = df['Player Name'].isin(df2_names)  # Adds a boolean column for df2
df['In_df3'] = df['Player Name'].isin(df3_names)  # Adds a boolean column for df3

# Alternatively, to get matching names
matching_in_df2 = df[df['In_df2']]
matching_in_df3 = df[df['In_df3']]

# Print the DataFrame with new columns indicating presence in df2 and df3
print("Original DataFrame with match indicators:")
print(df)

# Print the matching players
print("\nMatching players in df2:")
print(matching_in_df2)

print("\nMatching players in df3:")
print(matching_in_df3)

# Optionally, you can save the updated DataFrame to a new CSV
df

Original DataFrame with match indicators:
        Player Name  In_df2  In_df3
0     Glenn Maxwell    True    True
1    Jasprit Bumrah    True    True
2       Tim Southee    True    True
3     Aiden Markram    True    True
4     Andre Russell    True    True
5  Liam Livingstone    True    True
6      David Warner    True   False
7       Jos Buttler    True   False
8     Rajat Patidar    True   False
9  Suryakumar Yadav    True   False

Matching players in df2:
        Player Name  In_df2  In_df3
0     Glenn Maxwell    True    True
1    Jasprit Bumrah    True    True
2       Tim Southee    True    True
3     Aiden Markram    True    True
4     Andre Russell    True    True
5  Liam Livingstone    True    True
6      David Warner    True   False
7       Jos Buttler    True   False
8     Rajat Patidar    True   False
9  Suryakumar Yadav    True   False

Matching players in df3:
        Player Name  In_df2  In_df3
0     Glenn Maxwell    True    True
1    Jasprit Bumrah    True    True
2       Tim Southee    True    True
3     Aiden Markram    True    True
4     Andre Russell    True    True
5  Liam Livingstone    True    True

        Player Name  In_df2  In_df3
0     Glenn Maxwell    True    True
1    Jasprit Bumrah    True    True
2       Tim Southee    True    True
3     Aiden Markram    True    True
4     Andre Russell    True    True
5  Liam Livingstone    True    True
6      David Warner    True   False
7       Jos Buttler    True   False
8     Rajat Patidar    True   False
9  Suryakumar Yadav    True   False

In [3]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import time

# Load the batting data
batting_df = pd.read_csv('batting.csv')

# Create a mapping of player names to their profile links
player_links = {}
for index, row in batting_df.iterrows():
    player_name = row['batsmanName']  # Adjust if the column name is different
    player_link = row['player_link']  # Adjust if the column name is different
    player_links[player_name] = player_link

# Function to scrape the country and playing role information from player profile
def get_player_info(profile_url):
    try:
        response = requests.get(profile_url)
        if response.status_code == 200:
            soup = BeautifulSoup(response.text, 'html.parser')
            
            # Fetch country information
            country_elem = soup.find('a', title=lambda x: x and "cricket team profile" in x)
            country = country_elem.find('span', class_='ds-text-title-s').text.strip() if country_elem else "Country not found"
            
            # Fetch playing role information using the provided method
            player_details = soup.find('div', class_='ds-grid lg:ds-grid-cols-3 ds-grid-cols-2 ds-gap-4 ds-mb-8')
            playing_role_elem = player_details.find('p', text='Playing Role') if player_details else None
            playing_role = playing_role_elem.find_next('span').text.strip() if playing_role_elem else "Role not found"
            
            return country, playing_role
        else:
            print(f"Failed to retrieve data for URL: {profile_url}")
    except Exception as e:
        print(f"Error fetching information for {profile_url}: {e}")
    return "Country not found", "Role not found"

# Check country and role for each player in df
countries = []
roles = []
for index, row in df.iterrows():
    player_name = row['Player Name']
    if player_name in player_links:
        profile_url = player_links[player_name]
        country, role = get_player_info(profile_url)
        countries.append(country)
        roles.append(role)
        time.sleep(1)  # Add delay to avoid overwhelming the server
    else:
        countries.append("Not Found")
        roles.append("Not Found")

# Add the country and role information to the DataFrame
df['Country'] = countries
df['Role'] = roles

# Print the updated DataFrame
print("Updated DataFrame with country and role information:")
print(df)

C:\Users\kiran\AppData\Local\Temp\ipykernel_23088\3202768010.py:29: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  playing_role_elem = player_details.find('p', text='Playing Role') if player_details else None

Updated DataFrame with country and role information:
        Player Name  In_df2  In_df3       Country                 Role
0     Glenn Maxwell    True    True     Australia   Batting Allrounder
1    Jasprit Bumrah    True    True         India               Bowler
2       Tim Southee    True    True   New Zealand               Bowler
3     Aiden Markram    True    True  South Africa       Opening Batter
4     Andre Russell    True    True   West Indies           Allrounder
5  Liam Livingstone    True    True       England   Batting Allrounder
6      David Warner    True   False     Australia       Opening Batter
7       Jos Buttler    True   False       England  Wicketkeeper Batter
8     Rajat Patidar    True   False         India     Top order Batter
9  Suryakumar Yadav    True   False         India               Batter

In [4]:
df = df.drop(columns=['In_df2', 'In_df3'])
df.to_csv('final_players_ipl_2022_with_info.csv', index=False)
df

        Player Name       Country                 Role
0     Glenn Maxwell     Australia   Batting Allrounder
1    Jasprit Bumrah         India               Bowler
2       Tim Southee   New Zealand               Bowler
3     Aiden Markram  South Africa       Opening Batter
4     Andre Russell   West Indies           Allrounder
5  Liam Livingstone       England   Batting Allrounder
6      David Warner     Australia       Opening Batter
7       Jos Buttler       England  Wicketkeeper Batter
8     Rajat Patidar         India     Top order Batter
9  Suryakumar Yadav         India               Batter

In [5]:
import pandas as pd

# Select players with country name 'India'
indian_players = df[df['Country'] == 'India']

# Print the result
print("Indian Players:")
print(indian_players)

# Optionally, save the Indian players to a new CSV file
indian_players.to_csv('indian_players.csv', index=False)
print("Indian players saved to indian_players.csv")

Indian Players:
        Player Name Country              Role
1    Jasprit Bumrah   India            Bowler
8     Rajat Patidar   India  Top order Batter
9  Suryakumar Yadav   India            Batter
Indian players saved to indian_players.csv